# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Buchauer Lab
tagline:          'Computational Immunology'
description:      'Systems Biology of Infectious Diseases'
url:              http://libuchauer.github.io/
baseurl:          /

author:
  name:           'Lisa Buchauer'
