# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lisa Buchauer
tagline:          'Systems Biology of Infectious Diseases'
description:      'Computational Immunology Lab'
url:              http://libuchauer.github.io/
baseurl:          /

author:
  name:           'Lisa Buchauer'
  url:            https://twitter.com/libuchauer
